### ISSUE TITLE
Tangling is fast in my Emacs.

### ISSUE THREAD

**Issue by tmalsburg** [thblt/org-babel-tangle.py#3]
Perhaps you're hitting a bug?  I guess the org developers might appreciate a bur report.

**Comment by thblt** [comment]
Hum, indeed emacs -q tangles ~10x faster than configured Emacs.  I'll have to check that.

**Comment by thblt** [comment]
It's not a bug, it's a feature (of my config).  IIUC, Org creates a new buffer for *each and every src block*.  Which means everything that happens when the language's major mode gets loaded happens once for each src block.  Hence, slowdowns.  That's also why my Python version, naive as the implementation is, is way faster: it doesn't do anything with the block contents, it certainly doesn't treat them as code, it just routes them to different files.

**Comment by mrbig033** [comment]
I don't know if my config has the same issue, but tangling in Org is ridiculously slow, even for a small file. `org-babel-tangle` is more than 100 times faster.
